### ISSUE TITLE
Invoking getter/setter behavior?

### ISSUE THREAD

**Issue by tabatkins** [js-choi/proposal-bind-this#17]
I was thinking about how `::` is meant to be analogous to `.`, but realized this proposal currently only covers the "dot-call" version of the operator, `foo.bar()`. It leaves out the getter/setter invocation behavior of plain `foo.bar`. Should we consider this?

(I won't speculate on mechanics of it right now - we'd have to be slightly creative to get it to work, since there's no way to define a "free getter" like you can free function. Probably a symbol on the `bar` object or something could work.)

This would allow syntax like `foo::bar = 1`, or even chained `foo::bar::baz = 1` (invoking the "bar" getter-fn with "foo", then the "baz" setter-fn on that result). This would let you ergonomically handle WeakMaps-as-Ephemerons, for example: `foo::bar` could translate to `bar.get(foo)`, and `foo::bar = 1` to `bar.set(foo, 1)`.

Even if we don't want to do it right now, should we consider it as a likely future extension? This would imply, most importantly, that the RHS of the `::` operator is an ident (or parenthesized expression), so things like `foo::bar.baz()` would parse as `(foo::bar).baz()`, not `foo::(bar.baz)()`.

**Comment by js-choi** [comment]
Right, rather than being about extracting a getter/setter, it’s about letting receivers customize how they respond to being the receiver of `::`.

Like Tab said, the biggest question is if this is worth future proofing for a future extension, by switching `::`’s RHS from #16’s decorator syntax (allowing `.` chains) back to identifier/parentheses only.

Also important: as far as I can tell, it would also break the prototype-pollution use case of `::` by allowing third-party code to mess with `::`’s behavior, but maybe I’m wrong.

**Comment by theScottyJam** [comment]
The weakmap as Ephemeron doesn't seem like a strong use case for such a syntax either. It would mean each weakmap key would have to have these symbols defined on them. This sort of put things backwards - ideally, you would want weakmap behavior defined on the weakmap, not on the weakmap keys. In other words, it means the built-in WeakMap API couldn't provide such functionality for you, because you would have to be in charge of injecting each key with these symbols.

A syntax that more closely fits this sort of use-case would be, perhaps, the [overloadable data access operator](https://es.discourse.group/t/overloadable-data-accesor-operator/662/10) I've brought up previously on the TC39 forms. I've since mentioned that I don't think such a proposal is a great fit, because I don't think it's worth the extra syntax compared to alternative possibilities, but it's still an interesting thread.

**Comment by tabatkins** [comment]
> It would mean each weakmap key would have to have these symbols defined on them. This sort of put things backwards - ideally, you would want weakmap behavior defined on the weakmap, not on the weakmap keys. In other words, it means the built-in WeakMap API couldn't provide such functionality for you, because you would have to be in charge of injecting each key with these symbols.

Apologies, but I think you misunderstand either weakmaps-as-ephemerons, or the mechanics of my proposal. [My example](https://github.com/js-choi/proposal-bind-this/issues/17#issuecomment-946005508) shows it off - this *does* put the weakmap behavior on the weakmap, and the keys have no knowledge that there's a weakmap involved at all. It's just that it lets you write `obj::weakmap` and have it mean `weakmap.get(obj)`, emulating the syntax of a property but giving you the privacy/ocap powers of a weakmap.

**Comment by theScottyJam** [comment]
Oops, you're right, I glanced over the specifics too quickly. I had assumed the symbols got defined on the key, not the object.

**Comment by theScottyJam** [comment]
This also doesn't seem like it has any relation to binding. It's just reusing the syntax for another, alternative use case. Unless I'm missing something...

**Comment by theScottyJam** [comment]
> calling with a separately provided this

Is it even that though? You're providing a separate `this` to what? The only function being invoked in this picture is `b[Symbol.bindGet]`, and it's always going to be invoked with `this = b`.

**Comment by tabatkins** [comment]
Yeah, I see the value of making this unforgeable on functions, or only invokeable via an exotic object wrapper rather than being installable on arbitrary objects.

So really the question is just if we want to reserve the possibility for this in the future, and make `a::b.c()` parse in the required way (as `(a::b).c()`), rather than what #16 is allowing (`a::(b.c)()`).

**Comment by theScottyJam** [comment]
Is the differences in order of operations necessary to make this future compatible? Couldn't this getter/setter idea work ok with `a::b.c()` == `a::(b.c)()`? Or, what's the problem with it?

**Comment by zloirock** [comment]
```js
const size = {
  [Symbol.referenceGet](it){
    return Object.keys(it).length;
  },
  [Symbol.referenceSet](it, length){
    for (const key of Object.keys(it).slice(length)) delete it[key];
  }
}

console.log({ q: 1, w: 2, e: 3 }::size); // => 3

const dict = { q: 1, w: 2, e: 3 };
dict::size = 2;
console.log(dict); // => { q: 1, w: 2 };
```

**Comment by jridgewell** [comment]
I think this is an interesting direction, actually. If we stop thinking of `::` as the "bind" operator, and think of it as a key operator (or [reference](https://github.com/js-choi/proposal-bind-this/issues/17#issuecomment-946365557)). Instead of onforgeable bind/call syntax, it provides a way of dereferencing `.call`, `.get`, and `.set` on the RHS with the LHS.

```js
obj::foo;         // foo.get.call(obj)?
obj::foo = value; // foo.set.call(obj, value)?
obj::foo()        // foo.call(obj)
```

I honestly care less about the unforgeable call syntax, and more about the ability to express OOP-like behaviors with static functions. Babel already has to implement essentially this transform already in order to support `.#priv` private field access ([REPL](https://babeljs.io/repl#?browsers=Chrome%2075&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=MYGwhgzhAEBiD29oG8BQ1oGIAOAnAlgG7rQkAuAphGQBQCUKJGZAFvhAHQ4GEDcT0Vuy54i0ALzQAjPwzM2nbkQDUy2XKGLRheuoC-qPUA&debug=false&forceAllTransforms=false&shippedProposals=true&circleciRepo=&evaluate=true&fileSize=false&timeTravel=true&sourceType=module&lineWrap=false&presets=env&prettier=false&targets=&version=7.15.8&externalPlugins=&assumptions=%7B%7D)). I think this opens up a lot of new possibilities that are interesting.
